### ISSUE TITLE
Error: undefined method `to_sym' when closing PR

### ISSUE THREAD

**Issue by chrisft25** [pullpreview/action#28]
Hi! Suddenly I'm just getting this error when I close a PR (without the `pullpreview` label):

```
/app/lib/pull_preview/github_sync.rb:86:in `sync!': undefined method `to_sym' for nil:NilClass (NoMethodError)
	from /app/lib/pull_preview/github_sync.rb:26:in `run'
	from /app/bin/pullpreview:79:in `<main>'
```

I checked your repository and I can't see the problem

**Comment by crohr** [comment]
@chrisft25 is this still happening?

**Comment by chrisft25** [comment]
> @chrisft25 is this still happening?

Yes @crohr , this is still happening every time we close or merge a PR

**Comment by arsduo** [comment]
We're seeing the same whenever we try to build a pull preview via a Github label. The action fails to run. Happy to provide any additional info that would be useful!

**Comment by makeitraina** [comment]
+1 also having this problem

**Comment by RyanNielson** [comment]
I'm seeing this on PRs that don't have the `pullpreview` label. It makes an error show up in the PR, but isn't blocking. I think it's because `GithubSync#guess_action_from_event` may not be handling all possible cases and is returning `nil`. Perhaps that method should just return `return :ignored` at the end to handle any missing cases?

**Comment by crohr** [comment]
@RyanNielson I'll push the fix you mention, but I'm curious: could you send me the content of your `on:` section from your pullpreview workflow file?

**Comment by crohr** [comment]
And yes the filter on the label is necessary to avoid useless runs, for instance:

```
name: pullpreview
on:
  schedule:
    - cron: "30 0 * * *"
  push:
    branches:
      - master
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event.label.name == 'pullpreview' || contains(github.event.pull_request.labels.*.name, 'pullpreview')
```

**Comment by RyanNielson** [comment]
@crohr Here ya go:

```
name: PullPreview
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened, opened]
```

Also thanks for the quick turnaround, I'll see if I can try it sometime today.
