### ISSUE TITLE
Spinup PullPreview environment on PR Creation

### ISSUE THREAD

**Issue by Alanoll** [pullpreview/action#85]
I'd like to spin up environments for every PR by default. Would it be possible to add support to have PullPreview spin up environments on Pull Request open/reopen? 

I tried to do the following in a workflow, but it didn't appear to work.
1. Add Label to PR via Action
2. Execute PullPreview

**Comment by crohr** [comment]
Hello, indeed by default workflows that perform side effects cannot trigger other workflows (to avoid infinite loops). In that case I should provide an option to trigger the action without checking the label. I will have a look.

**Comment by Alanoll** [comment]
Here's what I was trying to do:
```
name: PullRequest PullPreview

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened, opened]


# make sure only one workflow runs at the same time
concurrency:
  group: pullpreview-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-pullpreview:
    permissions:
      contents: read # to fetch code (actions/checkout)
      deployments: write # to delete deployments
      pull-requests: write # to remove labels
      statuses: write # to create commit status
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Add the pullpreview label so the environments are created
      - name: Add Label to PR
        if: github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened'
        uses: actions/github-script@v6
        env:
          LABEL_NAME: pullpreview
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [process.env.LABEL_NAME]
            })

      - uses: pullpreview/action@v5.6.1
        # see https://github.com/pullpreview/action/wiki/Inputs
        with:
          compose_files: docker-compose.pullpreview.yml
          ports: 80/tcp,443/tcp
          ttl: 7d
          instance_type: micro
        env:
          AWS_ACCESS_KEY_ID: "${{ secrets.PULLPREVIEW_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.PULLPREVIEW_AWS_SECRET_ACCESS_KEY }}"
          AWS_REGION: "${{ vars.PULLPREVIEW_AWS_REGION }}"
```

I don't think the PR object that PullPreview looks at was updated with the new Label. Maybe all that's needed is that PullPreview needs to call the Github API to retrieve the latest "PR" object?
