### ISSUE TITLE
Deploying frontend + backend together

### ISSUE THREAD

**Issue by joh-klein** [pullpreview/action#97]
I have frontend app and a backend app that I want to deploy onto the same server. I tried to deploy it onto two servers, but frontend and backend both need the others PULLPREVIEW_PUBLIC_DNS.

Is there a way to have/add a custom prefix to the subdomain?

```
- uses: pullpreview/action@v5
  with:
    compose_files: docker-compose.yml
    prefix: ['web', 'api']
    instance_type: micro
    dns: preview.dytab.net
```

Which I can then use in my docker-compose.yml like this
```
  web:
    container_name: web
    environment:
      API_URL=https://api-${PULLPREVIEW_PUBLIC_DNS}

  api:
    container_name: api
    environment:
      APP_URL=https://web-${PULLPREVIEW_PUBLIC_DNS}
```
