### ISSUE TITLE
Scheduled workflow fails with "Resource not accessible by integration"

### ISSUE THREAD

**Issue by joh-klein** [pullpreview/action#99]
I have added a `schedule` trigger to the pullpreview workflow.

```
name: PullPreview
on:
  schedule:
    - cron: '30 */2 * * *'

deploy:
  …

destroy:
  if: |
    github.event_name == 'schedule' ||
    (github.event.action == 'unlabeled' && github.event.label.name == 'pullpreview') ||
    (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'pullpreview'))
  permissions:
    deployments: write # to delete deployments
    pull-requests: write # to remove labels
    statuses: write # to create commit status
  timeout-minutes: 30
  steps:
    - uses: pullpreview/action@v5
      env:
        AWS_ACCESS_KEY_ID: '${{ secrets.PULLPREVIEW_ACCESS_KEY }}'
        AWS_SECRET_ACCESS_KEY: '${{ secrets.PULLPREVIEW_SECRET_KEY }}'
        AWS_REGION: 'eu-central-1'

```

The `destroy` job works perfectly when I delete the label. But when it runs on schedule, I get this error:

```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
I, [2025-01-30T06:39:08.702342 #1]  INFO -- : [clear_dangling_deployments] start
Error: GET https://api.github.com/repos/[REDACTED]/[REDACTED]/issues?labels=pullpreview&per_page=100&pulls=true&state=all: 403 - Resource not accessible by integration // See: https://docs.github.com/rest/issues/issues#list-repository-issues
E, [2025-01-30T06:39:08.896087 #1] ERROR -- : /usr/local/bundle/gems/octokit-8.0.0/lib/octokit/response/raise_error.rb:14:in `on_complete'
/usr/local/bundle/gems/faraday-2.7.12/lib/faraday/middleware.rb:18:in `block in call'
/usr/local/bundle/gems/faraday-2.7.12/lib/faraday/response.rb:42:in `on_complete'
/usr/local/bundle/gems/faraday-2.7.12/lib/faraday/middleware.rb:17:in `call'
/usr/local/bundle/gems/octokit-8.0.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/usr/local/bundle/gems/octokit-8.0.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/usr/local/bundle/gems/faraday-2.7.12/lib/faraday/rack_builder.rb:153:in `build_response'
/usr/local/bundle/gems/faraday-2.7.12/lib/faraday/connection.rb:444:in `run_request'
/usr/local/bundle/gems/faraday-2.7.12/lib/faraday/connection.rb:200:in `get'
/usr/local/bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
/usr/local/bundle/gems/octokit-8.0.0/lib/octokit/connection.rb:156:in `request'
/usr/local/bundle/gems/octokit-8.0.0/lib/octokit/connection.rb:19:in `get'
/app/lib/pull_preview/github_sync.rb:48:in `clear_dangling_deployments'
/app/lib/pull_preview/github_sync.rb:18:in `run'
/app/bin/pullpreview:86:in `<main>'
```
